name: ISO Builder Regolith Image

on:
  push:
    tags:
      - 'v*'     # (optional) only tags starting with "v"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap debootstick zip

      - name: Build
        id: build_image
        working-directory: .github/scripts
        run: |
          sudo ./gen-debootstick.sh $RUNNER_TEMP ${{ github.ref_name }}
          set -e
          set -x
          IMAGE_FILE=$(find $RUNNER_TEMP -maxdepth 1 -name "regolith-*.img")
          ZIP_FILE_NAME="${IMAGE_FILE}.zip"
          zip -j "$ZIP_FILE_NAME" "$IMAGE_FILE"
          echo "ZIP_FILE=$ZIP_FILE_NAME" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Regolith ISO Build ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ env.ZIP_FILE }}
defaults:
  run:
    shell: bash